name: Main Build Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-library:
    uses: ./workflows/_build.yml 
    with:
      project:  |
        src/Nalix/Nalix.csproj
        src/Nalix.Common/Nalix.Common.csproj
        src/Nalix.Cryptography/Nalix.Cryptography.csproj
        src/Nalix.Logging/Nalix.Logging.csproj
        src/Nalix.Network/Nalix.Network.csproj
        src/Nalix.Network.Package/Nalix.Network.Package.csproj
        src/Nalix.Network.Web/Nalix.Network.Web.csproj
        src/Nalix.Shared/Nalix.Shared.csproj
        src/Nalix.Storage/Nalix.Storage.csproj
      test: tests/Nalix.Tests.sln 
      deploy: false
