name: Publish to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      - name: Authenticate with GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name github \
            --username ${{ github.actor }} \
            --password $NUGET_AUTH_TOKEN \
            --store-password-in-clear-text
        
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Pack
        run: dotnet pack --configuration Release --output ./packages

      - name: Publish Package
        run: dotnet nuget push ./packages/*.nupkg --source "github" --api-key $NUGET_AUTH_TOKEN --skip-duplicate
